name: ${project.artifactId}
version: ${project.version}
api-version: "1.13"
main: net.okocraft.retcon.Retcon
author: akaregi
commands:
  retcon:
    description: Base command for Retcon.
    usage: /<command> help
    permission: retcon.admin
    permission-message: '§cYou do not have permission <permission>'

permissions:
  retcon.admin:
    description: Retcon's administrative permission.
    default: op
